### ISSUE TITLE
make proper project with setup.py and use sphinx/sphinx-gallery to make a documentation.

### ISSUE THREAD

**Issue by agramfort** [yousrabk/bayes_meeg#1]
@yousrabk maybe @jasmainak can give you a hand in exchange of some French lessons...

the project should mimic as much as possible 

https://autoreject.github.io/

@yousrabk do you think you can give it a try?

**Comment by jasmainak** [comment]
I'll make a PR. @yousrabk can comment on it :)

**Comment by yousrabk** [comment]
Thank you Mainak :)
